version: '3'
services:
    kt-mall-web:
        image: registry.cn-shenzhen.aliyuncs.com/hlta/kt-mall:kt-mall-web_v1.1
        restart: "always"
        container_name: kt-mall-web
        ports:
            - 8190:80
        volumes:
            #  宿主机：容器
            - "/data/logs/kt-mall-web:/var/log/nginx/:rw"
            - "/etc/localtime:/etc/localtime"
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
            - TZ=Asia/Shanghai
    kt-mall-h5:
        image: registry.cn-shenzhen.aliyuncs.com/hlta/kt-mall:kt-mall-h5_v1.1
        restart: "always"
        container_name: kt-mall-h5
        ports:
            - 8191:80
        volumes:
            #  宿主机：容器
            - "/data/logs/kt-mall-h5:/var/log/nginx/:rw"
            - "/etc/localtime:/etc/localtime"
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
            - TZ=Asia/Shanghai